accounts/urls.py
from django.contrib.auth import views as account_views
from django.urls import path

import accounts.views as user_views

app_name="accounts"

urlpatterns = [
    path("", user_views.index, name="index"),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        account_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        account_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
]

pravaham/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="base.html"), name='index'),
    path("accounts/", include('accounts.urls')),
    path("posts/", include('posts.urls')),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from commons.db_mixins import CommonAbstractModel


class User(AbstractUser, CommonAbstractModel):
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    username = None
    email = models.EmailField(unique=True)

    def __str__(self):
        return str(self.uuid)

    def __repr__(self):
        return f"{self.__class__.__name__}: {self.email}"

posts/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from commons.db_mixins import CommonAbstractModel


class Post(CommonAbstractModel):
    text = models.TextField()
    creator = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    tags = ArrayField(base_field=models.TextField(), default=list)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model= User
        fields = ['email', 'password1', 'password2']

accounts/views.py
import logging

from django.contrib import messages
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse

from accounts.forms import UserRegisterForm

logger = logging.getLogger(__name__)


def index(request):
    if request.user.is_authenticated:
        return redirect(reverse("posts:lobby"))
    return redirect(reverse("accounts:login"))


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request,
                "Your account has been created",
            )
            return redirect("posts:lobby")
        else:
            logger.warning("Failed registeration: %s", form.errors)

    else:
        form = UserRegisterForm()
    return render(request, "accounts/register.html", {"form": form})

pravaham/views.py
from django.http import HttpRequest, HttpResponse
from django.views.decorators.http import require_http_methods


@require_http_methods(["GET"])
async def async_health(request: HttpRequest, *args, **kwargs):
    return HttpResponse(status=200)

@require_http_methods(["GET"])
async def sync_health(request: HttpRequest, *args, **kwargs):
    return HttpResponse(status=200)

templates/accounts/login.html
{% extends 'base.html' %} {% block base %}
<div class="content-section" id="login">
  <form method="POST">
    <legend class="border-bottom mb-4">LOGIN</legend>
    {% csrf_token %}
    <div class="login">
      <table>
        <tr>
          <td>
            <label for="id_username">Email:</label>
          </td>
          <td>
            <input
              type="text"
              name="username"
              autofocus
              autocapitalize="none"
              autocomplete="username"
              maxlength="254"
              required
              id="id_username"
            />
          </td>
        </tr>
        <tr>
          <td>
            <label for="id_password">Password:</label>
          </td>
          <td>
            <input
              type="password"
              name="password"
              autocomplete="current-password"
              required
              id="id_password"
            />
          </td>
        </tr>

        <tr>
          <td colspan="2">
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Log In</button>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </form>
  <div class="border-top pt-3">
    <small>
      Register Here <a href="{% url 'accounts:register' %}">Sign Up</a>
    </small>
  </div>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% block base %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small>
            <a href="{% url 'accounts:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %} {% block base %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <legend class="border-bottom mb-4">Register Now</legend>
    <div class="register">
      <table>
        <tr>
          <td>
            <label for="id_email">Email:</label>
          </td>
          <td>
            <input
              type="email"
              name="email"
              maxlength="254"
              autofocus
              required
              id="id_email"
            />
          </td>
        </tr>
        <tr>
          <td>
            <label for="id_password1">Password:</label>
          </td>
          <td>
            <input
              type="password"
              name="password1"
              autocomplete="new-password"
              required
              aria-describedby="id_password1_helptext"
              id="id_password1"
            />
          </td>
        </tr>
        <tr>
          <td>
            <label for="id_password2">Password confirmation:</label>
          </td>
          <td>
            <input
              type="password"
              name="password2"
              autocomplete="new-password"
              required
              aria-describedby="id_password2_helptext"
              id="id_password2"
            />
          </td>

          <td>
            <span class="helptext" id="id_password2_helptext"
              >Enter the same password as before, for verification.</span
            >
          </td>
        </tr>
        <tr>
          <td colspan="3">
            <p>
              <span class="helptext" id="id_password1_helptext"
                ><ul>
                  <li>
                    Your password can’t be too similar to your other personal
                    information.
                  </li>
                  <li>Your password must contain at least 8 characters.</li>
                  <li>Your password can’t be a commonly used password.</li>
                  <li>Your password can’t be entirely numeric.</li>
                </ul></span
              >
            </p>

            <p></p>
          </td>
        </tr>
        <tr>
          <td colspan="3">
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">
                Sign Up
              </button>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </form>
  <div class="border-top pt-3">
    <small>
      Already Have An Account?
      <a class="ml-2" href="{% url 'accounts:login' %}">Log In</a>
    </small>
  </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Realtime Example</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static "css/style.css" %}" >
    <script src="{% static 'js/script.js' %}"></script>
  </head>


  <body hx-ext="ws" class="container">
    <nav>
      <ul class="menu">
      {% if user.is_authenticated %}
        <li class="header-link"><a href="{% url 'posts:lobby' %}">User Posts</a></li>
        <li class="header-link"><a href="{% url 'posts:create' %}">Create Post</a></li>
        <li class="logout">
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn-link">Logout</type=>
          </form>
        </li>
      {% else %}
        <li class="header-link"><a href="{% url 'accounts:login' %}">Login</a></li>
      {% endif %}
      </ul>
    </nav>
    <div class="container">
    {% block base %} {% endblock %} {% block script %} {% endblock %}
    </div>
  </body>
</html>

templates/posts/create.html
{% extends 'base.html' %}

{% block base %}

<h2> Create post for {{ user_email }}</h2>
<form method='post' action='{% url "posts:create" %}'>
        {% csrf_token %}
        <input name='text' id='text' placeholder='Your Text here'>
        <button>Post</button>
</form>
{% endblock %}

templates/posts/lobby.html
{% extends 'base.html' %} {% block base %}
<h4 style="display: none" id="newMessage">New Mastodon Posts</h4>
<div id="notifications"></div>

<h2> Posts for {{ user_email }}</h2>
<div hx-ext="sse" sse-connect="{{ stream_server }}">
  <div hx-get="{% url 'posts:new-content' %}" hx-trigger="sse:new-notification" hx-swap="afterbegin">
  </div>
  <div sse-swap="status" hx-swap="afterbegin"></div>
</div>

<div id="messages">
  {% for message in messages %}
  <div class="messageBox">
    <div class="message">

    {{ message.text | safe }}
    </div>
    <div class="user">
      {{ message.creator }}
      <span class="time"> {{ message.created_at }} </span>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %} {% block script %}
<script src="https://unpkg.com/htmx.org@1.9.10/dist/ext/sse.js"></script>
{% endblock %}

templates/posts/new_posts.html
<div id="messages">
  {% for message in messages %}
  <div class="messageBox">
    <div class="message">{{ message.text }}</div>
    <div class="user">
       {{ message.creator }}
      <span class="time"> {{ message.created_at }} </span>
    </div>
  </div>
  {% endfor %}
</div>

templates/realtime/latest_content.html
    </div>
    {% for message in messages %}
    <div style="border: 1px solid black; margin: 5px; padding: 5px;">
        <span class="createdAt">
            {{ message.created_at }}
        </span>
        <strong class="user">
           {{ message.creator }}
        </strong>:
        <span class="message">
            {{ message.text }}
        </span>
    </div>
    {% endfor %}


    <template id="message">
        <div style="border: 1px solid black; margin: 5px; padding: 5px;">
            <strong class="createdAt"></strong> :
            <strong class="user"></strong> :
            <span class="message"></span>
        </div>
    </template>

templates/realtime/live_qa/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Realtime Example</title>
    {% load static %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static "css/style.css" %}" >
    <link rel="stylesheet" href="{% static "css/mastodon.css" %}" >
    <script src="{% static 'js/script.js' %}"></script>
  </head>


  <body hx-ext="ws" class="container">
    <nav>
      <ul class="menu">
      </ul>
    </nav>
    <div class="container">
    {% block base %} {% endblock %} 
    </div>
  </body>
    {% block script %} {% endblock %}
</html>

templates/realtime/live_qa/create.html
{% extends 'realtime/live_qa/base.html' %}

{% block base %}
<form method='post' action='{% url "realtime:qa-send" %}'>
        {% csrf_token %}
        <input name='name' id='name' placeholder='Name'>
        <input name='question' id='question' placeholder='Question'>
        <button>Post</button>
</form>
{% endblock %}

templates/realtime/live_qa/new_questions.html
<div id="messages">
    {% for message in messages %}
    <div class="messageBox">
      <div class="user">{{ message.name }}</div>
      <div class="message">
          {{ message.question | safe }}
      </div>
    </div>
    {% endfor %}
  </div>
  

templates/realtime/live_qa/questions.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Questions</title>
    <script src="https://unpkg.com/htmx.org@1.6.0/dist/htmx.js"></script>
    <link rel="stylesheet" href="{% static "css/style.css" %}" > <link
    rel="stylesheet" href="{% static "css/mastodon.css" %}" >
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        margin: 0;
      }

      header,
      footer {
        padding: 10px;
        background-color: #333;
        color: white;
        height: 100%;
        width: 100%;
      }
      #chat-wrapper {
        position: fixed;
        top: 110px;
        bottom: 110px;
        overflow-y: auto;

        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
      }
      main {
        overflow-y: auto;
        padding: 10px;
      }

      #messages {
        margin-bottom: 10px;
      }

      form {
        display: flex;
        background-color: #323a3d;
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
      }

      input[type="text"] {
        flex-grow: 1;
        margin-right: 10px;
        font-size: 14px;
        color: rgb(159, 154, 154);
      }

      button {
        padding: 8px 16px;
        border: none;
        background-color: #333;
        color: white;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>Questions</h1>
    </header>

    <div id="chat-wrapper">
      <div id="notifications"></div>
      <div id="messages">
        {% for message in messages %}
        <div class="messageBox">
          <div class="user">{{ message.name }}</div>
          <div class="message">{{ message.question | safe }}</div>
        </div>
        {% endfor %}
      </div>
    </div>

    <footer>
      <form id="chat-form" onsubmit="submitForm(event)">
        {% csrf_token %}
        <input
          type="text"
          name="question"
          id="question"
          placeholder="Type your question here..."
        />
        <input type="hidden" name="name" value="{{ name }}" />
        <button type="submit">Send</button>
      </form>
    </footer>

    <script>
      const source = new EventSource("{{ stream_url }}", {
        withCredentials: true,
      });
      console.log("Connected to {{ stream_url }}");

      source.addEventListener("new-notification", (event) => {
        const payload = JSON.parse(event.data);
        console.log(payload);
        fetch(`/realtime/qa/new/${payload.new_message_id}/`)
          .then((response) => response.text())
          .then((data) => {
            existing = notifications.innerHTML;
            notifications.innerHTML = data + existing;
            x = document.getElementById("newMessage");
            x.style.display = "block";
            htmx.process(notifications);
          });
      });

      function submitForm(event) {
        event.preventDefault();
        var form = document.getElementById("chat-form");
        var formData = new FormData(form);

        fetch('{% url "realtime:qa-send" %}', {
          method: "POST",
          body: formData,
        })
          .then((response) => response.text())
          .then((data) => {
            document.getElementById("question").value = ""; // Clear input field
          })
          .catch((error) => {
            console.error("Form submission error:", error);
          });
      }
    </script>
  </body>
</html>

templates/realtime/live_qa/start.html
{% extends 'realtime/live_qa/base.html' %} {% block base %}
<input name="name" id="name" placeholder="Name" />
<input type="button" id="submitButton" name="theButton" value="Enter" />
{% endblock %} {% block script %}
<script>
  var url = '{% url "realtime:qa-questions" "name"%}';
  document.getElementById("submitButton").addEventListener("click", () => {
    var name = encodeURIComponent(document.getElementById("name").value);
    url = url.replace("name", name);
    if (name) {
      document.getElementById("name").value = ""; // Clear input field
      window.location.href = url;
    }
  });
</script>
{% endblock %}